### ISSUE TITLE
Add tags for Ansible version 2.1

### ISSUE THREAD

**Issue by clement87** [weldpua2008/docker-ansible#1]
Hi,
can you add a tag for the last version of Ansible (2.1.0.0) ?
Thanks

**Comment by weldpua2008** [comment]
Hi,
There is some issue https://github.com/ansible/ansible/issues/16454 that I need to fix.

PS:
Currently only centos 5 was build: https://hub.docker.com/r/weldpua2008/docker-ansible/tags/ so you can use it:
docker run -ti --rm weldpua2008/docker-ansible:centos5_v2.1.0.0 bash

**Comment by weldpua2008** [comment]
Fixed for Ubuntu

**Comment by weldpua2008** [comment]
Currently only Alpine Linux 3.2 wasn't build

**Comment by weldpua2008** [comment]
Succesfully builded [![Build Status](https://travis-ci.org/weldpua2008/docker-ansible.svg?branch=2.1.0.0)](https://travis-ci.org/weldpua2008/docker-ansible)
